version: 2.1

jobs:
  deploy_kestra_flow:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install curl & jq
          command: |
            sudo apt-get update && sudo apt-get install -y curl jq

      - run:
          name: Deploy Kestra Flow from GitHub
          command: |
            curl -s https://raw.githubusercontent.com/smentz1/kestra-flows-test/main/flows/deploy-test-1.yml | \
            curl -v -X POST \
              -u "${KESTRA_USER}:${KESTRA_PASS}" \
              -H "Content-Type: application/x-yaml" \
              --data-binary @- \
              https://kestra.rec.beymedias.com/api/v1/flows

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_kestra_flow:
          filters:
            branches:
              only: main
