id: push_flows_to_git
namespace: tutorial

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: circleci
    
tasks:


  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    username: smentz1
    password: "{{secret('GITHUB_ACCESS_TOKEN')}}"
    url: https://github.com/smentz1/kestra-flows-test.git
    branch: main
    sourceNamespace: tutorial
    gitDirectory: flows
    commitMessage: "flows from kestra"
    dryRun: false
