id: push_to_git2
namespace: null

tasks:
  - id: monitoring_start
    type: io.kestra.plugin.core.http.Request
    uri: https://healthchecks.p.agefi.fr/ping/47e160cc-710a-4a84-be97-d118acbc9883/start
    method: GET
    sslOptions:
      insecureTrustAllCertificates: true
  - id: monitoring_start_cronitor
    type: io.kestra.plugin.core.http.Request
    uri: https://cronitor.link/p/edf66fd88670481995e009f74d6dd065/76Q01P?state=run
    method: GET
    sslOptions:
      insecureTrustAllCertificates: true


      
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    url: https://github.com/beymedias/kestra-test
    sourceNamespace: beymedias
    targetNamespace: beymedias
    flows: "*"
    branch: main
    username: beymedias
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    commitMessage: add namespace files changes
  - id: monitoring_end
    type: io.kestra.plugin.core.http.Request
    uri: https://healthchecks.p.agefi.fr/ping/47e160cc-710a-4a84-be97-d118acbc9883
    method: GET
    sslOptions:
      insecureTrustAllCertificates: true
  - id: monitoring_end_cronitor
    type: io.kestra.plugin.core.http.Request
    uri: https://cronitor.link/p/edf66fd88670481995e009f74d6dd065/76Q01P?state=complete
    method: GET
    sslOptions:
      insecureTrustAllCertificates: true
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 */1 * * *" # every hour
disabled: true