triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "30 4 * * *"

id: UPDATE_PIANO_OPINION
namespace: null

tasks:
      - id: pianoApi_opinion
        type: io.kestra.plugin.core.flow.Sequential
        tasks:
         - id: pianoApi_opinion_term
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_API_LIST
           inputs:
            site: OPINION
            type: /term/list
         - id: pianoApi_opinion_ressource
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_API_LIST
           inputs:
             site: OPINION
             type: /resource/list

         - id: pianoReport_opinion_user
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_FETCH_REPORT
           inputs:
             site: OPINION
             type: userExport
         - id: pianoReport_opinion_transactions
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_FETCH_REPORT
           inputs:
             site: OPINION
             type: transactionsReport
         - id: pianoReport_opinion_access
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_FETCH_REPORT
           inputs:
             site: OPINION
             type: accessReportExport
         - id: pianoReport_opinion_subscription
           type: io.kestra.plugin.core.flow.Subflow
           namespace:  null
           flowId: PIANO_FETCH_REPORT
           inputs:
             site: OPINION
             type: subscriptionLog

disabled: true