id: UPDATE_LOGGIA
namespace: null

tasks:
  - id: Magellan_Sequential
    type: io.kestra.plugin.core.flow.Sequential
    tasks:
      - id: start
        type: io.kestra.plugin.core.log.Log
        message: LOGGIA task start        
      - id: monitoring_start
        type: io.kestra.plugin.core.http.Request
        uri: https://healthchecks.rec.beymedias.com/ping/7d2421f4-c814-4ccc-b670-d7b6409b5a0f/start
        method: GET
        sslOptions:
          insecureTrustAllCertificates: true
      - id: magellan_flow
        type: io.kestra.plugin.core.flow.Subflow
        namespace:  null
        flowId: LOGGIA_SYNC_BIGQUERY
      - id: monitoring_end
        type: io.kestra.plugin.core.http.Request
        uri: https://healthchecks.rec.beymedias.com/ping/7d2421f4-c814-4ccc-b670-d7b6409b5a0f
        method: GET
        sslOptions:
          insecureTrustAllCertificates: true
      - id: end
        type: io.kestra.plugin.core.log.Log
        message: LOGGIA task end

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 6 * * 1-5"